add_library(gravitas_model_materials STATIC GtsModelMaterialRealization.cpp)
target_link_libraries(gravitas_model_materials PUBLIC gravitas_model_realization gravitas_material_frontend PRIVATE gravitas_model_image_processing)
target_compile_features(gravitas_model_materials PUBLIC cxx_std_20)
add_library(gravitas_model_world STATIC GtsModelInstanceRuntime.cpp GtsModels.cpp)
target_link_libraries(gravitas_model_world PUBLIC gravitas_model_instances gravitas_model_materials)
target_compile_features(gravitas_model_world PUBLIC cxx_std_20)
