#include <algorithm>
#include <array>
#include <iostream>
#include <vector>

#include "input/EngineControlBindings.hpp"
#include "input/UiDefaultBindings.hpp"
#include "ecssetup/camera/input/CameraDefaultBindings.hpp"
#include "ToolDefaultBindings.hpp"

int main()
{
    const std::vector<InputBinding> expected{
        InputBinding{"engine.pause",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::X)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_cancel",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Escape)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.close",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Escape)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.toggle_ui",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F2)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.debug_overlay",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F3)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_nav_next",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Tab)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.ui_nav_previous",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Tab), ModifierFlags::Shift},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.debug_overlay_page",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Tab)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.screenshot",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F12)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.tools_toggle",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F6)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_primary",
                     InputTrigger{InputTrigger::Type::MouseButton, 0},
                     ActivationMode::Held,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_submit",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Enter)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.ui_submit",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Space)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.tools_select",
                     InputTrigger{InputTrigger::Type::MouseButton, 0},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.ui_nav_up",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowUp)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.zoom_in",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowUp)},
                     ActivationMode::Held,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_nav_down",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowDown)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.zoom_out",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowDown)},
                     ActivationMode::Held,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_nav_left",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowLeft)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.orbit_left",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowLeft)},
                     ActivationMode::Held,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.ui_nav_right",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowRight)},
                     ActivationMode::Pressed,
                     "",
                     PausePolicy::AlwaysActive,
                     true},
        InputBinding{"engine.orbit_right",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowRight)},
                     ActivationMode::Held,
                     "",
                     PausePolicy::AlwaysActive},
        InputBinding{"engine.tool_camera_yaw_left",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Q)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_yaw_right",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::E)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_pitch_up",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowUp)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_pitch_down",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowDown)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_forward",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::W)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_backward",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::S)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_left",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::A)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_right",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::D)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_up",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::R)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_down",
                     InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F)},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_camera_look",
                     InputTrigger{InputTrigger::Type::MouseButton, 1},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
        InputBinding{"engine.tool_viewport_pan",
                     InputTrigger{InputTrigger::Type::MouseButton, 2},
                     ActivationMode::Held,
                     "engine.tools",
                     PausePolicy::AlwaysActive,
                     false},
    };
    using namespace gts::input::defaults;
    std::array<void (*)(InputBindingRegistry&), 4> installers{
        engine::install, ui::install, camera::install, tools::install};
    for (int order = 0; order < 2; ++order)
    {
        InputBindingRegistry registry;
        for (auto install : installers)
            install(registry);
        for (auto install : installers)
            install(registry);
        const auto actual = registry.exportBindings();
        if (!std::is_permutation(actual.begin(), actual.end(), expected.begin(), expected.end()))
        {
            std::cerr << "Feature installation changed or duplicated defaults.\n";
            return 1;
        }
        const InputTrigger replacement{InputTrigger::Type::Key, static_cast<int>(GtsKey::P)};
        registry.rebind("engine.pause", registry.getTriggersForAction("engine.pause").front(), replacement);
        for (auto install : installers)
            install(registry);
        if (registry.getTriggersForAction("engine.pause") != std::vector<InputTrigger>{replacement})
        {
            std::cerr << "Default registration overwrote a rebind.\n";
            return 1;
        }
        std::reverse(installers.begin(), installers.end());
    }
    return 0;
}
