add_library(gravitas_model_cooking STATIC GtsModelCooker.cpp)
target_link_libraries(gravitas_model_cooking PUBLIC gravitas_model_serialization gravitas_asset_cooking
    PRIVATE gravitas_model_image_processing gravitas_obj_importer gravitas_gltf_importer gravitas_image_decode gravitas_static_geometry)
target_compile_features(gravitas_model_cooking PUBLIC cxx_std_20)

target_include_directories(gravitas_model_cooking PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
