add_library(gravitas_model_controller_contracts INTERFACE)
target_link_libraries(gravitas_model_controller_contracts INTERFACE gravitas_core)
target_include_directories(gravitas_model_controller_contracts INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/public")

add_subdirectory(domain)
add_subdirectory(import)
add_subdirectory(processing/geometry)
add_subdirectory(processing/image)
add_subdirectory(serialization)
add_subdirectory(cooking)
add_subdirectory(loading)
add_subdirectory(realization)
add_subdirectory(runtime)
add_subdirectory(world)
add_subdirectory(extraction)
