add_library(gravitas_model_instances STATIC GtsModelInstance.cpp GtsModelHierarchy.cpp)
target_link_libraries(gravitas_model_instances PUBLIC gravitas_model_realization gravitas_skeletal_animation gravitas_skin_palette)
target_compile_features(gravitas_model_instances PUBLIC cxx_std_20)

target_include_directories(gravitas_model_instances PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")

target_link_libraries(gravitas_model_instances PUBLIC gravitas_asset_contracts)
