find_package(Git QUIET)
set(revision "unknown")
set(dirty "unknown")
set(source_state "unknown")
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ENGINE_ROOT}" rev-parse HEAD
        OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE git_result ERROR_QUIET)
    if(NOT git_result EQUAL 0)
        set(revision "unknown")
    else()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ENGINE_ROOT}" status --porcelain
            OUTPUT_VARIABLE status OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(status STREQUAL "")
            set(dirty "false")
        else()
            set(dirty "true")
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ENGINE_ROOT}" diff --no-ext-diff HEAD
            OUTPUT_VARIABLE changes)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ENGINE_ROOT}" ls-files --others --exclude-standard
            OUTPUT_VARIABLE untracked OUTPUT_STRIP_TRAILING_WHITESPACE)
        string(REPLACE "\n" ";" untracked "${untracked}")
        foreach(path IN LISTS untracked)
            set(absolute_path "${ENGINE_ROOT}/${path}")
            cmake_path(IS_PREFIX BUILD_ROOT "${absolute_path}" NORMALIZE generated_in_build)
            if(NOT generated_in_build AND EXISTS "${absolute_path}" AND NOT IS_DIRECTORY "${absolute_path}")
                file(SHA256 "${absolute_path}" hash)
                string(APPEND changes "\n${path}:${hash}")
            endif()
        endforeach()
        string(SHA256 source_state "${changes}")
    endif()
endif()
file(SHA256 "${FIXTURE}" fixture_sha)
set(json "{}")
function(metadata key value)
    string(REPLACE "\\" "\\\\" escaped "${value}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    string(REPLACE "\n" "\\n" escaped "${escaped}")
    string(REPLACE "\r" "\\r" escaped "${escaped}")
    string(REPLACE "\t" "\\t" escaped "${escaped}")
    string(JSON json SET "${json}" "${key}" "\"${escaped}\"")
    set(json "${json}" PARENT_SCOPE)
endfunction()
metadata(engine_revision "${revision}")
metadata(working_tree_dirty "${dirty}")
metadata(working_changes_sha256 "${source_state}")
metadata(configuration "${CONFIG}")
metadata(compiler "${COMPILER}")
metadata(compiler_path "${COMPILER_PATH}")
metadata(cxx_standard "20")
metadata(cxx_flags "${FLAGS}")
metadata(platform "${PLATFORM}")
metadata(fixture "canonical-cooking/triangle.obj")
metadata(fixture_sha256 "${fixture_sha}")
file(WRITE "${OUTPUT}.tmp" "#pragma once\ninline constexpr const char* BuildMetadataJson = R\"GTS_METADATA(${json})GTS_METADATA\";\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp" "${OUTPUT}" COMMAND_ERROR_IS_FATAL ANY)
file(REMOVE "${OUTPUT}.tmp")
