#pragma once

#include "InputBindingRegistry.h"
#include "GtsKey.h"

namespace gts::input::defaults::tools
{
    inline void install(InputBindingRegistry& registry)
    {
        const InputBinding bindings[]{
            InputBinding{"engine.tools_toggle",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F6)},
                         ActivationMode::Pressed,
                         "",
                         PausePolicy::AlwaysActive},
            InputBinding{"engine.tools_select",
                         InputTrigger{InputTrigger::Type::MouseButton, 0},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_yaw_left",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::Q)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_yaw_right",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::E)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_pitch_up",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowUp)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_pitch_down",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::ArrowDown)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_forward",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::W)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_backward",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::S)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_left",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::A)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_right",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::D)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_up",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::R)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_down",
                         InputTrigger{InputTrigger::Type::Key, static_cast<int>(GtsKey::F)},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_camera_look",
                         InputTrigger{InputTrigger::Type::MouseButton, 1},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
            InputBinding{"engine.tool_viewport_pan",
                         InputTrigger{InputTrigger::Type::MouseButton, 2},
                         ActivationMode::Held,
                         "engine.tools",
                         PausePolicy::AlwaysActive,
                         false},
        };
        registry.bindDefaults(bindings);
    }
}
