# Source ownership is the authority; target names alone cannot establish a layer.
function(gravitas_source_layer path root result)
    file(TO_CMAKE_PATH "${path}" normalized)
    foreach(layer core modules runtime)
        if(normalized STREQUAL "${root}/${layer}" OR normalized MATCHES "^${root}/${layer}/")
            set(${result} "${layer}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${result} "" PARENT_SCOPE)
endfunction()

function(gravitas_collect_targets directory result)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        gravitas_collect_targets("${child}" nested)
        list(APPEND targets ${nested})
    endforeach()
    set(${result} "${targets}" PARENT_SCOPE)
endfunction()

function(gravitas_check_source_layers)
    get_property(root GLOBAL PROPERTY GRAVITAS_SOURCE_LAYER_ROOT)
    gravitas_collect_targets("${CMAKE_SOURCE_DIR}" targets)
    foreach(owner IN LISTS targets)
        get_target_property(directory "${owner}" SOURCE_DIR)
        gravitas_source_layer("${directory}" "${root}" layer)
        if(NOT layer STREQUAL "core" AND NOT layer STREQUAL "modules")
            continue()
        endif()

        # Traverse actual links, including PRIVATE/LINK_ONLY links and aliases.
        # Wrapping an upward dependency in an interface target cannot hide it.
        set(pending "${owner}")
        set(visited "")
        while(pending)
            list(POP_FRONT pending dependency)
            if(dependency IN_LIST visited)
                continue()
            endif()
            list(APPEND visited "${dependency}")
            get_target_property(alias "${dependency}" ALIASED_TARGET)
            if(alias)
                list(APPEND pending "${alias}")
                continue()
            endif()
            get_target_property(dependency_dir "${dependency}" SOURCE_DIR)
            gravitas_source_layer("${dependency_dir}" "${root}" dependency_layer)
            if(dependency STREQUAL "gravitas_engine")
                set(dependency_layer runtime)
            endif()
            if(dependency_layer STREQUAL "runtime" OR
               (layer STREQUAL "core" AND dependency_layer STREQUAL "modules"))
                message(FATAL_ERROR "Gravitas source boundary: ${owner} (${layer}) depends on ${dependency} (${dependency_layer})")
            endif()
            foreach(property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES SOURCES INTERFACE_SOURCES)
                get_target_property(entries "${dependency}" "${property}")
                foreach(entry IN LISTS entries)
                    if(NOT entry MATCHES "\\$<" AND
                       (property STREQUAL "SOURCES" OR property STREQUAL "INTERFACE_SOURCES"))
                        get_filename_component(entry "${entry}" ABSOLUTE BASE_DIR "${dependency_dir}")
                    endif()
                    # These checks apply to both plain and generator-expression paths.
                    if(entry MATCHES "${root}/runtime(/|>|$)" OR
                       (layer STREQUAL "core" AND entry MATCHES "${root}/modules(/|>|$)") OR
                       entry STREQUAL "${root}" OR entry MATCHES "${root}>$")
                        message(FATAL_ERROR "Gravitas source boundary: ${owner} (${layer}) obtains forbidden ${property} from ${dependency}: ${entry}")
                    endif()
                endforeach()
            endforeach()
            foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                get_target_property(links "${dependency}" "${property}")
                string(REGEX MATCHALL "([A-Za-z_][A-Za-z_0-9+.-]*::)*[A-Za-z_][A-Za-z_0-9+.-]*" candidates "${links}")
                foreach(candidate IN LISTS candidates)
                    if(TARGET "${candidate}")
                        list(APPEND pending "${candidate}")
                    endif()
                endforeach()
            endforeach()
        endwhile()
    endforeach()

    # Catch explicit relative/absolute includes and short runtime header names,
    # even when a target has not yet compiled the offending header.
    file(GLOB_RECURSE runtime_headers "${root}/runtime/*.h" "${root}/runtime/*.hpp")
    file(GLOB_RECURSE module_headers "${root}/modules/*.h" "${root}/modules/*.hpp")
    foreach(layer core modules)
        set(forbidden_headers ${runtime_headers})
        if(layer STREQUAL "core")
            list(APPEND forbidden_headers ${module_headers})
        endif()
        set(forbidden_names "")
        foreach(header IN LISTS forbidden_headers)
            get_filename_component(name "${header}" NAME)
            list(APPEND forbidden_names "${name}")
        endforeach()
        file(GLOB_RECURSE sources "${root}/${layer}/*.h" "${root}/${layer}/*.hpp" "${root}/${layer}/*.cpp")
        foreach(source IN LISTS sources)
            file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]")
            foreach(include IN LISTS includes)
                string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"].*" "\\1" header "${include}")
                get_filename_component(source_dir "${source}" DIRECTORY)
                get_filename_component(resolved "${header}" ABSOLUTE BASE_DIR "${source_dir}")
                gravitas_source_layer("${resolved}" "${root}" included_layer)
                if(included_layer STREQUAL "runtime" OR
                   (layer STREQUAL "core" AND included_layer STREQUAL "modules"))
                    message(FATAL_ERROR "Gravitas source boundary: ${source} includes ${header} from a forbidden layer")
                endif()
                get_filename_component(name "${header}" NAME)
                if(header MATCHES "(^|/)runtime/" OR
                   (layer STREQUAL "core" AND header MATCHES "(^|/)modules/") OR
                   name IN_LIST forbidden_names)
                    # Capability-local runtime directories are legitimate. Resolve
                    # paths against the forbidden owners before rejecting them.
                    foreach(forbidden IN LISTS forbidden_headers)
                        string(REPLACE "." "\\." suffix "${header}")
                        if(forbidden MATCHES "/${suffix}$" OR
                           (header MATCHES "(^|/)runtime/" AND forbidden MATCHES "/${name}$"))
                            message(FATAL_ERROR "Gravitas source boundary: ${source} includes ${header} from a forbidden layer")
                        endif()
                    endforeach()
                endif()
            endforeach()
        endforeach()
    endforeach()
endfunction()
