# Supplement the three-layer check with a narrow public include-root rule.
function(gravitas_check_public_includes)
    get_property(root GLOBAL PROPERTY GRAVITAS_SOURCE_LAYER_ROOT)
    gravitas_collect_targets("${CMAKE_SOURCE_DIR}" targets)
    foreach(target IN LISTS targets)
        get_target_property(owner "${target}" SOURCE_DIR)
        gravitas_source_layer("${owner}" "${root}" layer)
        if(NOT layer)
            continue()
        endif()
        get_target_property(includes "${target}" INTERFACE_INCLUDE_DIRECTORIES)
        foreach(path IN LISTS includes)
            # Inspect the conventional build-tree wrapper without evaluating arbitrary expressions.
            string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" path "${path}")
            if(path MATCHES "\\$<" OR path MATCHES "-NOTFOUND$")
                continue()
            endif()
            get_filename_component(path "${path}" ABSOLUTE BASE_DIR "${owner}")
            file(REAL_PATH "${path}" path)
            file(REAL_PATH "${owner}" owner_path)
            file(RELATIVE_PATH owner_from_include "${path}" "${owner_path}")
            if(path STREQUAL "${root}" OR path STREQUAL "${root}/modules" OR
               path STREQUAL "${root}/modules/rendering" OR
               (NOT path STREQUAL owner_path AND NOT owner_from_include MATCHES "^\\.\\."))
                message(FATAL_ERROR "Gravitas public include ownership: ${target} exports broad ancestor/root ${path}")
            endif()
        endforeach()
    endforeach()
endfunction()
