# Source ownership is the authority; target names alone cannot establish a layer.
# Resolve lexical aliases and existing symlinks without evaluating generator expressions.
function(gravitas_canonical_path path base result)
    get_filename_component(absolute "${path}" ABSOLUTE BASE_DIR "${base}")
    if(EXISTS "${absolute}")
        file(REAL_PATH "${absolute}" canonical)
    else()
        # Short/system includes and generated paths need not exist relative to
        # the source file. Resolve their existing parent without REAL_PATH warnings.
        get_filename_component(parent "${absolute}" DIRECTORY)
        get_filename_component(name "${absolute}" NAME)
        gravitas_canonical_path("${parent}" "${base}" canonical_parent)
        set(canonical "${canonical_parent}/${name}")
    endif()
    file(TO_CMAKE_PATH "${canonical}" canonical)
    set(${result} "${canonical}" PARENT_SCOPE)
endfunction()

function(gravitas_source_layer path root result)
    gravitas_canonical_path("${path}" "${CMAKE_CURRENT_SOURCE_DIR}" normalized)
    gravitas_canonical_path("${root}" "${CMAKE_CURRENT_SOURCE_DIR}" normalized_root)
    foreach(layer core modules runtime)
        string(FIND "${normalized}/" "${normalized_root}/${layer}/" prefix)
        if(prefix EQUAL 0)
            set(${result} "${layer}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${result} "" PARENT_SCOPE)
endfunction()

function(gravitas_boundary_sources directory result)
    set(patterns "")
    foreach(extension h hpp hh hxx H inl ipp tpp inc c cc cpp cxx C)
        list(APPEND patterns "${directory}/*.${extension}")
    endforeach()
    # Additions/removals trigger regeneration; content edits trigger it via the
    # directory property. A normal build therefore reruns both deferred checkers.
    file(GLOB_RECURSE files CONFIGURE_DEPENDS LIST_DIRECTORIES false ${patterns})
    set_property(DIRECTORY "${CMAKE_SOURCE_DIR}" APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${files})
    set(${result} "${files}" PARENT_SCOPE)
endfunction()

function(gravitas_collect_targets directory result)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        gravitas_collect_targets("${child}" nested)
        list(APPEND targets ${nested})
    endforeach()
    set(${result} "${targets}" PARENT_SCOPE)
endfunction()

function(gravitas_check_source_layers)
    get_property(root GLOBAL PROPERTY GRAVITAS_SOURCE_LAYER_ROOT)
    gravitas_canonical_path("${root}" "${CMAKE_CURRENT_SOURCE_DIR}" root)
    gravitas_collect_targets("${CMAKE_SOURCE_DIR}" targets)
    foreach(owner IN LISTS targets)
        get_target_property(directory "${owner}" SOURCE_DIR)
        gravitas_source_layer("${directory}" "${root}" layer)
        if(NOT layer STREQUAL "core" AND NOT layer STREQUAL "modules")
            continue()
        endif()

        # Traverse actual links, including PRIVATE/LINK_ONLY links and aliases.
        # Wrapping an upward dependency in an interface target cannot hide it.
        set(pending "${owner}")
        set(visited "")
        while(pending)
            list(POP_FRONT pending dependency)
            if(dependency IN_LIST visited)
                continue()
            endif()
            list(APPEND visited "${dependency}")
            get_target_property(alias "${dependency}" ALIASED_TARGET)
            if(alias)
                list(APPEND pending "${alias}")
                continue()
            endif()
            get_target_property(dependency_dir "${dependency}" SOURCE_DIR)
            gravitas_source_layer("${dependency_dir}" "${root}" dependency_layer)
            if(dependency STREQUAL "gravitas_engine")
                set(dependency_layer runtime)
            endif()
            if(dependency_layer STREQUAL "runtime" OR
               (layer STREQUAL "core" AND dependency_layer STREQUAL "modules"))
                message(FATAL_ERROR "Gravitas source boundary: ${owner} (${layer}) depends on ${dependency} (${dependency_layer})")
            endif()
            foreach(property INCLUDE_DIRECTORIES INTERFACE_INCLUDE_DIRECTORIES SOURCES INTERFACE_SOURCES)
                get_target_property(entries "${dependency}" "${property}")
                foreach(entry IN LISTS entries)
                    # Object files carry their producing target's ownership even
                    # when injected through SOURCES rather than target_link_libraries.
                    string(REGEX MATCHALL "\\$<TARGET_OBJECTS:[A-Za-z_][A-Za-z_0-9:.+-]*>" objects "${entry}")
                    foreach(object IN LISTS objects)
                        string(REGEX REPLACE "^\\$<TARGET_OBJECTS:([^>]+)>$" "\\1" object "${object}")
                        if(TARGET "${object}")
                            list(APPEND pending "${object}")
                        endif()
                    endforeach()
                    string(REGEX REPLACE "^\\$<BUILD_INTERFACE:(.*)>$" "\\1" checked "${entry}")
                    if(NOT checked MATCHES "\\$<" AND NOT checked MATCHES "-NOTFOUND$")
                        gravitas_canonical_path("${checked}" "${dependency_dir}" checked)
                        gravitas_source_layer("${checked}" "${root}" checked_layer)
                        if(checked_layer STREQUAL "runtime" OR
                           (layer STREQUAL "core" AND checked_layer STREQUAL "modules") OR
                           checked STREQUAL root)
                            message(FATAL_ERROR "Gravitas source boundary: ${owner} (${layer}) obtains forbidden ${property} from ${dependency}: ${entry}")
                        endif()
                    endif()
                    # Retain detection of literal forbidden roots embedded in other
                    # generator expressions; arbitrary expressions are not evaluated.
                    if(checked MATCHES "\\$<")
                        if(entry MATCHES "${root}/runtime(/|>|$)" OR
                           (layer STREQUAL "core" AND entry MATCHES "${root}/modules(/|>|$)") OR
                           entry STREQUAL "${root}" OR entry MATCHES "${root}>$")
                            message(FATAL_ERROR "Gravitas source boundary: ${owner} (${layer}) obtains forbidden ${property} from ${dependency}: ${entry}")
                        endif()
                    endif()
                endforeach()
            endforeach()
            foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                get_target_property(links "${dependency}" "${property}")
                string(REGEX MATCHALL "([A-Za-z_][A-Za-z_0-9+.-]*::)*[A-Za-z_][A-Za-z_0-9+.-]*" candidates "${links}")
                foreach(candidate IN LISTS candidates)
                    if(TARGET "${candidate}")
                        list(APPEND pending "${candidate}")
                    endif()
                endforeach()
            endforeach()
        endwhile()
    endforeach()

    # Catch explicit relative/absolute includes and short runtime header names,
    # even when a target has not yet compiled the offending header.
    gravitas_boundary_sources("${root}/runtime" runtime_headers)
    gravitas_boundary_sources("${root}/modules" module_headers)
    foreach(layer core modules)
        set(forbidden_headers ${runtime_headers})
        if(layer STREQUAL "core")
            list(APPEND forbidden_headers ${module_headers})
        endif()
        set(forbidden_names "")
        foreach(header IN LISTS forbidden_headers)
            get_filename_component(name "${header}" NAME)
            list(APPEND forbidden_names "${name}")
        endforeach()
        gravitas_boundary_sources("${root}/${layer}" sources)
        foreach(source IN LISTS sources)
            file(STRINGS "${source}" includes REGEX "^[ \t]*#[ \t]*include[ \t]*[<\"]")
            foreach(include IN LISTS includes)
                string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"].*" "\\1" header "${include}")
                get_filename_component(source_dir "${source}" DIRECTORY)
                gravitas_canonical_path("${header}" "${source_dir}" resolved)
                gravitas_source_layer("${resolved}" "${root}" included_layer)
                if(included_layer STREQUAL "runtime" OR
                   (layer STREQUAL "core" AND included_layer STREQUAL "modules"))
                    message(FATAL_ERROR "Gravitas source boundary: ${source} includes ${header} from a forbidden layer")
                endif()
                get_filename_component(name "${header}" NAME)
                if(header MATCHES "(^|/)runtime/" OR
                   (layer STREQUAL "core" AND header MATCHES "(^|/)modules/") OR
                   name IN_LIST forbidden_names)
                    # Capability-local runtime directories are legitimate. Resolve
                    # paths against the forbidden owners before rejecting them.
                    foreach(forbidden IN LISTS forbidden_headers)
                        string(REPLACE "." "\\." suffix "${header}")
                        if(forbidden MATCHES "/${suffix}$" OR
                           (header MATCHES "(^|/)runtime/" AND forbidden MATCHES "/${name}$"))
                            message(FATAL_ERROR "Gravitas source boundary: ${source} includes ${header} from a forbidden layer")
                        endif()
                    endforeach()
                endif()
            endforeach()
        endforeach()
    endforeach()
endfunction()
