if(NOT DEFINED CHECK_FILE OR NOT DEFINED FIXTURE_ROOT OR NOT DEFINED CASE)
    message(FATAL_ERROR "CHECK_FILE, FIXTURE_ROOT and CASE are required")
endif()

set(source "${FIXTURE_ROOT}/${CASE}/source")
set(binary "${FIXTURE_ROOT}/${CASE}/build")
file(REMOVE_RECURSE "${source}" "${binary}")
file(MAKE_DIRECTORY "${source}/core" "${source}/modules" "${source}/runtime")
file(WRITE "${source}/core/CMakeLists.txt" "add_library(foundation INTERFACE)\n")
file(WRITE "${source}/modules/CMakeLists.txt"
    "add_library(capability INTERFACE)\ntarget_link_libraries(capability INTERFACE foundation)\n")
file(WRITE "${source}/runtime/CMakeLists.txt"
    "add_library(composition INTERFACE)\ntarget_link_libraries(composition INTERFACE capability foundation)\n")
file(WRITE "${source}/runtime/Composition.h" "#pragma once\n")
file(WRITE "${source}/modules/Capability.h" "#pragma once\n")

set(injection "")
set(language NONE)
set(expect_allowed OFF)
set(incremental OFF)
if(CASE STREQUAL "allowed")
    file(WRITE "${source}/core/Valid.hpp" "#include <vector>\n")
    set(injection "target_include_directories(capability INTERFACE \"${source}/modules/future\")")
    set(expect_allowed ON)
elseif(CASE STREQUAL "core_modules")
    set(injection "target_link_libraries(foundation INTERFACE capability)")
elseif(CASE STREQUAL "core_runtime")
    set(injection "target_link_libraries(foundation INTERFACE composition)")
elseif(CASE STREQUAL "modules_runtime")
    set(injection "target_link_libraries(capability INTERFACE composition)")
elseif(CASE STREQUAL "transitive_alias")
    set(injection "add_library(hidden INTERFACE)\nadd_library(composition_alias ALIAS composition)\ntarget_link_libraries(hidden INTERFACE $<BUILD_INTERFACE:composition_alias>)\ntarget_link_libraries(capability INTERFACE hidden)")
elseif(CASE STREQUAL "include_directory")
    set(injection "target_include_directories(capability INTERFACE \"${source}/runtime\")")
elseif(CASE STREQUAL "root_include_directory")
    set(injection "target_include_directories(foundation INTERFACE \"${source}\")")
elseif(CASE STREQUAL "core_source_include")
    file(WRITE "${source}/core/Invalid.h" "#include \"Capability.h\"\n")
elseif(CASE STREQUAL "core_relative_include")
    file(WRITE "${source}/core/Invalid.h" "#include \"../modules/Capability.h\"\n")
elseif(CASE STREQUAL "module_runtime_source")
    set(injection "target_sources(capability INTERFACE \"${source}/runtime/Composition.h\")")
elseif(CASE STREQUAL "module_source_include")
    file(WRITE "${source}/modules/Invalid.h" "#include \"Composition.h\"\n")
elseif(CASE MATCHES "^objects_")
    set(language CXX)
    file(WRITE "${source}/runtime/Object.cpp" "int runtime_object = 0;\n")
    file(WRITE "${source}/modules/Object.cpp" "int module_object = 0;\n")
    file(APPEND "${source}/runtime/CMakeLists.txt" "add_library(runtime_objects OBJECT Object.cpp)\n")
    file(APPEND "${source}/modules/CMakeLists.txt" "add_library(module_objects OBJECT Object.cpp)\n")
    if(CASE STREQUAL "objects_core_module")
        set(injection "target_sources(foundation INTERFACE $<TARGET_OBJECTS:module_objects>)")
    elseif(CASE STREQUAL "objects_transitive")
        set(injection "add_library(hidden INTERFACE)\ntarget_sources(hidden INTERFACE $<BUILD_INTERFACE:$<TARGET_OBJECTS:runtime_objects>>)\ntarget_link_libraries(capability INTERFACE hidden)")
    elseif(CASE STREQUAL "objects_external_owner")
        set(injection "add_library(hidden_objects OBJECT \"${source}/modules/../runtime/Object.cpp\")\ntarget_sources(capability INTERFACE $<TARGET_OBJECTS:hidden_objects>)")
    elseif(CASE STREQUAL "objects_allowed")
        set(injection "target_sources(capability INTERFACE $<TARGET_OBJECTS:module_objects>)\ntarget_sources(composition INTERFACE $<TARGET_OBJECTS:runtime_objects>)")
        set(expect_allowed ON)
    else()
        file(APPEND "${source}/modules/CMakeLists.txt"
            "add_library(direct_consumer STATIC $<TARGET_OBJECTS:runtime_objects>)\n")
    endif()
elseif(CASE STREQUAL "normalized_include")
    set(injection "target_include_directories(capability INTERFACE $<BUILD_INTERFACE:${source}/modules/../runtime>)")
elseif(CASE STREQUAL "normalized_source")
    set(injection "target_sources(capability INTERFACE $<BUILD_INTERFACE:${source}/modules/../runtime/Composition.h>)")
elseif(CASE STREQUAL "sibling_allowed")
    set(injection "target_include_directories(capability INTERFACE \"${source}/runtime/../modules\")")
    set(expect_allowed ON)
elseif(CASE MATCHES "^symlink_")
    file(CREATE_LINK "${source}/runtime" "${source}/alias" SYMBOLIC RESULT link_result)
    if(NOT link_result STREQUAL "0")
        message(STATUS "Skipping symlink fixture: ${link_result}")
        return()
    endif()
    if(CASE STREQUAL "symlink_include")
        set(injection "target_include_directories(capability INTERFACE \"${source}/alias\")")
    elseif(CASE STREQUAL "symlink_source")
        set(injection "target_sources(capability INTERFACE \"${source}/alias/Composition.h\")")
    else()
        file(WRITE "${source}/modules/Invalid.h" "#include \"../alias/Composition.h\"\n")
    endif()
elseif(CASE MATCHES "^extension_(.+)$")
    set(extension "${CMAKE_MATCH_1}")
    file(WRITE "${source}/modules/Invalid.${extension}" "#include \"Composition.h\"\n")
    if(extension MATCHES "^(inl|ipp|tpp|inc|hh|hxx|H)$")
        file(WRITE "${source}/runtime/Hidden.${extension}" "#pragma once\n")
        file(WRITE "${source}/modules/Invalid.${extension}" "#include \"Hidden.${extension}\"\n")
    endif()
elseif(CASE MATCHES "^incremental_(edit|add)$")
    set(incremental ON)
    file(WRITE "${source}/modules/Changed.hpp" "// initially valid\n")
else()
    message(FATAL_ERROR "Unknown boundary test ${CASE}")
endif()

file(WRITE "${source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(SourceBoundaryFixture ${language})\nadd_subdirectory(core)\nadd_subdirectory(modules)\nadd_subdirectory(runtime)\n${injection}\ninclude(\"${CHECK_FILE}\")\nset_property(GLOBAL PROPERTY GRAVITAS_SOURCE_LAYER_ROOT \"${source}\")\ngravitas_check_source_layers()\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(incremental)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Initial incremental configure failed: ${output}\n${error}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
    if(CASE STREQUAL "incremental_add")
        set(changed "${source}/modules/Added.hpp")
    else()
        set(changed "${source}/modules/Changed.hpp")
    endif()
    file(WRITE "${changed}" "#include \"Composition.h\"\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${binary}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
endif()
if(expect_allowed)
    if("${output}\n${error}" MATCHES "does not refer to an existing path")
        message(FATAL_ERROR "Unresolved include paths must not emit canonicalization warnings: ${output}\n${error}")
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Allowed dependency graph rejected: ${output}\n${error}")
    endif()
elseif(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "Gravitas source boundary:")
    message(FATAL_ERROR "Expected boundary rejection for ${CASE}: ${output}\n${error}")
endif()
