if(NOT DEFINED CHECK_FILE OR NOT DEFINED FIXTURE_ROOT OR NOT DEFINED CASE)
    message(FATAL_ERROR "CHECK_FILE, FIXTURE_ROOT and CASE are required")
endif()

set(source "${FIXTURE_ROOT}/${CASE}/source")
set(binary "${FIXTURE_ROOT}/${CASE}/build")
file(MAKE_DIRECTORY "${source}/core" "${source}/modules" "${source}/runtime")
file(WRITE "${source}/core/CMakeLists.txt" "add_library(foundation INTERFACE)\n")
file(WRITE "${source}/modules/CMakeLists.txt"
    "add_library(capability INTERFACE)\ntarget_link_libraries(capability INTERFACE foundation)\n")
file(WRITE "${source}/runtime/CMakeLists.txt"
    "add_library(composition INTERFACE)\ntarget_link_libraries(composition INTERFACE capability foundation)\n")
file(WRITE "${source}/runtime/Composition.h" "#pragma once\n")
file(WRITE "${source}/modules/Capability.h" "#pragma once\n")

set(injection "")
if(CASE STREQUAL "allowed")
elseif(CASE STREQUAL "core_modules")
    set(injection "target_link_libraries(foundation INTERFACE capability)")
elseif(CASE STREQUAL "core_runtime")
    set(injection "target_link_libraries(foundation INTERFACE composition)")
elseif(CASE STREQUAL "modules_runtime")
    set(injection "target_link_libraries(capability INTERFACE composition)")
elseif(CASE STREQUAL "transitive_alias")
    set(injection "add_library(hidden INTERFACE)\nadd_library(composition_alias ALIAS composition)\ntarget_link_libraries(hidden INTERFACE $<BUILD_INTERFACE:composition_alias>)\ntarget_link_libraries(capability INTERFACE hidden)")
elseif(CASE STREQUAL "include_directory")
    set(injection "target_include_directories(capability INTERFACE \"${source}/runtime\")")
elseif(CASE STREQUAL "root_include_directory")
    set(injection "target_include_directories(foundation INTERFACE \"${source}\")")
elseif(CASE STREQUAL "core_source_include")
    file(WRITE "${source}/core/Invalid.h" "#include \"Capability.h\"\n")
elseif(CASE STREQUAL "core_relative_include")
    file(WRITE "${source}/core/Invalid.h" "#include \"../modules/Capability.h\"\n")
elseif(CASE STREQUAL "module_runtime_source")
    set(injection "target_sources(capability INTERFACE \"${source}/runtime/Composition.h\")")
elseif(CASE STREQUAL "module_source_include")
    file(WRITE "${source}/modules/Invalid.h" "#include \"Composition.h\"\n")
else()
    message(FATAL_ERROR "Unknown boundary test ${CASE}")
endif()

file(WRITE "${source}/CMakeLists.txt" "cmake_minimum_required(VERSION 3.20)\nproject(SourceBoundaryFixture NONE)\nadd_subdirectory(core)\nadd_subdirectory(modules)\nadd_subdirectory(runtime)\n${injection}\ninclude(\"${CHECK_FILE}\")\nset_property(GLOBAL PROPERTY GRAVITAS_SOURCE_LAYER_ROOT \"${source}\")\ngravitas_check_source_layers()\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(CASE STREQUAL "allowed")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Allowed dependency graph rejected: ${output}\n${error}")
    endif()
elseif(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "Gravitas source boundary:")
    message(FATAL_ERROR "Expected boundary rejection for ${CASE}: ${output}\n${error}")
endif()
